name: blood_pressure_diary
description: "Дневник давления"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_svg: ^2.0.10
  csv: ^6.0.0
  pdf: ^3.11.1
  share_plus: ^10.1.0
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  file_picker: ^8.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

